version: '3'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data

  couchdb:
    build: ./dragnet/couchdb
    volumes:
      - couchdata:/opt/couchdb/data
    ports:
      - 5984:5984
    env_file: ./dragnet/couchdb/.local_env

  elasticsearch:
    build: ./elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - network.host=0.0.0.0
      - transport.host=localhost
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file: .local_env
    volumes:
      - ./declarations_site:/usr/local/declarations_site
      - ./declarations_bank:/mnt/declarations_bank
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - elasticsearch
      - couchdb

  dragnet_utils:
    build: ./dragnet/utils
    volumes:
      - ./dragnet/utils:/usr/local/dragnet
      - ./dragnet/data:/mnt/dragnet_data
      - ./dragnet/views:/usr/local/dragnet/views
      - ./declarations_bank:/mnt/declarations_bank
    depends_on:
      - couchdb
      - elasticsearch

volumes:
  pgdata:
  esdata:
  couchdata:
