# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='channel',
            field=models.CharField(default='', max_length=250, verbose_name='ChannelID'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='answer',
            field=models.CharField(default='', max_length=250, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='conversation',
            field=models.CharField(default='', max_length=250, verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='from_id',
            field=models.CharField(default='', max_length=250, verbose_name='FromID'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='from_name',
            field=models.CharField(default='', max_length=250, verbose_name='FromName'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='query',
            field=models.CharField(default='', max_length=250, verbose_name='Запит'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='timestamp',
            field=models.CharField(default='', max_length=50, verbose_name='Timestamp'),
        ),
    ]
