# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20170520_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='auto_reply',
            field=models.BooleanField(default=False, verbose_name='Автомат'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створений'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='from_id',
            field=models.CharField(db_index=True, default='', max_length=250, verbose_name='FromID'),
        ),
    ]
