# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20170701_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='auto_reply',
            field=models.BooleanField(default=False, verbose_name='Розсилка'),
        ),
    ]
