# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-19 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='term_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='Ідентифікатор терміну'),
        ),
    ]
