# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180819_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='frequency',
            field=models.IntegerField(default=0, verbose_name='Кількість вживань у текстах'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='source',
            field=models.CharField(choices=[('g', 'Google translate'), ('p', 'Translations from PEP project'), ('t', 'Translator of declarations project'), ('u', 'Yet to translate')], max_length=1, verbose_name='Джерело перекладу'),
        ),
    ]
