# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190331_1515'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='translation',
            index_together=set([('frequency', 'source')]),
        ),
    ]
