# Generated by Django 2.2.10 on 2020-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190401_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='term_id',
            field=models.CharField(max_length=4096, primary_key=True, serialize=False, verbose_name='Ідентифікатор терміну'),
        ),
    ]
