# Generated by Django 2.2.11 on 2020-06-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_region_region_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Назва регіону [en]'),
        ),
    ]
