# Generated by Django 2.2.7 on 2019-11-05 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotter', '0002_searchtask_chat_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifysend',
            name='new_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='Нові документи'),
        ),
        migrations.AlterField(
            model_name='searchtask',
            name='found_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='Знайдені документи'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='found_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='Знайдені документи'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='new_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='Нові документи'),
        ),
    ]
