# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-12 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0020_auto_20180101_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='youtube_embed_link',
            field=models.URLField(blank=True, verbose_name='Embed для youtube'),
        ),
    ]
