# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0021_homepage_youtube_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='youtube_embed_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок youtube видео'),
        ),
    ]
