# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-04 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0023_auto_20180419_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebottommenulink',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepagetopmenulink',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
