# Generated by Django 2.2.10 on 2020-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0024_auto_20191105_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebottommenulink',
            name='link_external',
            field=models.CharField(blank=True, max_length=255, verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='homepagetopmenulink',
            name='link_external',
            field=models.CharField(blank=True, max_length=255, verbose_name='External link'),
        ),
    ]
