# Generated by Django 2.2.11 on 2020-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0026_auto_20200316_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawhtmlpage',
            name='body_en',
            field=models.TextField(verbose_name='[EN] Текст сторінки'),
        ),
    ]
