# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_id', models.CharField(max_length=60, verbose_name='Ідентифікатор декларації')),
                ('year', models.IntegerField(verbose_name='Рік подання декларації')),
                ('corrected', models.BooleanField(verbose_name='Уточнена декларація')),
                ('doc_type', models.CharField(max_length=50, verbose_name='Тип документу')),
            ],
            options={
                'verbose_name': 'Декларація фокус-персони',
                'verbose_name_plural': 'Декларація фокус-персони',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='Ідентифікатор сторінки')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок сторінки')),
                ('description', models.TextField(blank=True, verbose_name='Опис сторінки')),
                ('keywords', models.TextField(verbose_name='Ключові слова для пошуку в деклараціях (по одному запиту на рядок)')),
            ],
            options={
                'verbose_name': 'Лендінг-сторінка',
                'verbose_name_plural': 'Лендінг-сторінки',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я особи")),
                ('extra_keywords', models.CharField(max_length=200, verbose_name='Додаткові ключові слова для пошуку')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landings.LandingPage', verbose_name='Лендінг-сторінка')),
            ],
            options={
                'verbose_name': 'Фокус-персона',
                'verbose_name_plural': 'Фокус-персони',
            },
        ),
        migrations.AddField(
            model_name='declaration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landings.Person', verbose_name='Персона'),
        ),
        migrations.AlterIndexTogether(
            name='declaration',
            index_together=set([('year', 'corrected', 'doc_type')]),
        ),
    ]
