# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='exclude',
            field=models.BooleanField(default=False, verbose_name='Ігнорувати цей документ'),
        ),
        migrations.AlterIndexTogether(
            name='declaration',
            index_together=set([('year', 'corrected', 'doc_type', 'exclude')]),
        ),
    ]
