# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 10:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0002_auto_20190418_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='obj_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None, verbose_name='Ідентифікатори з декларації'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='source',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Машиночитний вміст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='landings.LandingPage', verbose_name='Лендінг-сторінка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Додаткові ключові слова для пошуку'),
        ),
        migrations.AlterUniqueTogether(
            name='declaration',
            unique_together=set([('person', 'declaration_id')]),
        ),
    ]
