# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 19:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0003_auto_20190419_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaration',
            options={'ordering': ['-year', '-corrected'], 'verbose_name': 'Декларація фокус-персони', 'verbose_name_plural': 'Декларація фокус-персони'},
        ),
        migrations.AlterField(
            model_name='declaration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='landings.Person', verbose_name='Персона'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='source',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Машиночитний вміст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_keywords',
            field=models.CharField(blank=True, help_text='Ключові слова для додаткового звуження пошуку', max_length=200, verbose_name='Додаткові ключові слова для пошуку'),
        ),
    ]
