# Generated by Django 2.2.10 on 2020-02-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0004_auto_20190427_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Ключові слова для пошуку в деклараціях (по одному запиту на рядок)'),
        ),
    ]
