# Generated by Django 2.2.11 on 2020-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0005_auto_20200220_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='user_declarant_id',
            field=models.IntegerField(default=None, null=True, verbose_name='Ідентифікатор декларанта'),
        ),
    ]
