# Generated by Django 2.2.11 on 2020-04-15 11:49

from django.db import migrations
from catalog.elastic_models import NACPDeclaration


def populate_declarant_id(apps, schema_editor):
    Declaration = apps.get_model('landings', 'Declaration')
    for d in Declaration.objects.filter(user_declarant_id__isnull=True):
        d.user_declarant_id = d.source["infocard"].get("user_declarant_id", None)
        if d.user_declarant_id is None:
            es_decl = NACPDeclaration.get(id=d.declaration_id)
            d.user_declarant_id = getattr(es_decl.intro, "user_declarant_id", None)

        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0006_declaration_user_declarant_id'),
    ]

    operations = [
        migrations.RunPython(
            populate_declarant_id,
            migrations.RunPython.noop,
        ),
    ]
