# Generated by Django 2.2.11 on 2020-05-07 22:04

import ckeditor.fields
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0007_auto_20200415_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='landings'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Опис сторінки'),
        ),
    ]
