# Generated by Django 2.2.11 on 2020-05-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200220_1322'),
        ('landings', '0008_auto_20200508_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='body_type',
            field=models.CharField(blank=True, choices=[('city_council', 'Міська рада'), ('regional_council', 'Обласна рада'), ('other', 'Інше')], max_length=30, null=True, verbose_name='Тип держоргану'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Region'),
        ),
    ]
