# Generated by Django 2.2.11 on 2020-06-09 20:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0009_auto_20200510_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Опис сторінки'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок сторінки'),
        ),
    ]
